version: '3'
services:
  feegow-web:
    platform: windows
    container_name: feegow-web
    hostname: feegow-web
    network_mode: nat
    build:
      context: .
      dockerfile: Dockerfile
    image: asp-classic:feegow
    ports:
      - "880:80"
    environment:
      FC_MYSQL_HOST: BRRJPE0AANM7 #host computer name
      FC_MYSQL_HOST_DEV: BRRJPE0AANM7 #host computer name
      FC_MYSQL_USER: root
      FC_MYSQL_PASSWORD: ""
      FC_MASTER: 123456
      FC_MYSQL_DATABASE: cliniccentral
      FC_MYSQL_DRIVER: "MySQL ODBC 8.0 ANSI Driver"
      FC_PWD_SALT: F33g0W_Pwd4_
      FC_APP_ENV: local
      MONGO_CONNECTION_STRING: mongodb://mongo:27017/mydatabase # Connection string for MongoDB
    volumes:
      - $HOME/VSCodeProjects/feegow/feegowclinic:C:/inetpub/wwwroot
    dns:
      - 8.8.8.8
    depends_on:
      - redis

#redis service definition for lcow
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    platform: linux
    ports:
      - "6379:6379"
    volumes:
      - $HOME/PhpstormProjects/feegow/docker-tests/iis/redis-data:/data



volumes:
    redis-data: