services:
  feegow-web:
    platform: windows
    container_name: feegow-web
    hostname: feegow-web
    network_mode: nat
    build:
      context: .
      dockerfile: Dockerfile
    image: asp-classic:feegow
    ports:
      - "880:80"
    environment:
      FC_MYSQL_HOST: BRRJPE0AANM7 #host.docker.internal
      FC_MYSQL_HOST_DEV: BRRJPE0AANM7 #host.docker.internal
      FC_MYSQL_USER: feegow
      FC_MYSQL_PASSWORD: 1234
      FC_MASTER: 123456
      FC_MYSQL_DATABASE: cliniccentral
      FC_MYSQL_DRIVER: "MySQL ODBC 8.0 ANSI Driver"
      FC_PWD_SALT: F33g0W_Pwd4_
      FC_APP_ENV: local
#      MONGO_CONNECTION_STRING: mongodb://mongo:27017/mydatabase # Connection string for MongoDB
    volumes:
      - D:/.projects/feegow/feegowclinic:C:/inetpub/wwwroot
    dns:
      - 8.8.8.8
#    depends_on:
#      - redis

#  redis:
#    image: redis
#    container_name: redis
#    hostname: redis
#    ports:
#      - "6379:6379"

#volumes:
#  mydata: