version: '3'
services:
  feegow-web:
    platform: windows
    container_name: feegow-web
    hostname: feegow-web
    network_mode: nat
    links:
      - feegow-mysql
    build:
      context: iis
      dockerfile: Dockerfile
    image: asp-classic:feegow
    ports:
      - "880:80"
      - "8008:8000"
    networks:
      feegow:
        ipv4_address: 1.1.1.2
    environment:
      FC_MYSQL_HOST=feegow-mysql: 3306
      FC_MYSQL_USER: root
      FC_MYSQL_PASSWORD: ""
      FC_MASTER: 123456
      FC_MYSQL_DATABASE: cliniccentral
      FC_MYSQL_DRIVER: "MySQL ODBC 8.0 ANSI Driver"
      FC_PWD_SALT: F33g0W_Pwd4_
      FC_APP_ENV: local
      APP_URL: "http://feegow-web:8000/"
      APP_URL_TEST: "http://feegow-web:8000/"
    volumes:
      - C:\Users\bruno\VSCodeProjects\feegowclinic-v7:C:/inetpub/wwwroot
      - C:\Users\bruno\PhpstormProjects\feegow\feegow-api:C:/feegow-api
    healthcheck:
      test: [ "CMD", "powershell", "-command", "Invoke-WebRequest -UseBasicParsing http://localhost:880 || exit 1" ]
      interval: 60s
      timeout: 30s
      retries: 30
    depends_on:
      feegow-mysql:
        condition: service_healthy

  feegow-mysql:
    platform: linux/x86_64
    container_name: feegow-mysql
    hostname: feegow-mysql
    network_mode: nat
    build:
      context: mysql
      dockerfile: Dockerfile
    image: mysql:5.7.38
    ports:
      - "3307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      ROW_FORMAT: "DYNAMIC"
      INNODB_DEFAULT_ROW_FORMAT: "dynamic"
      SQL_MODE: "ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
      INNODB_BUFFER_POOL_SIZE: "64M"
      INNODB_LOG_FILE_SIZE: "5M"
      INNODB_LOG_BUFFER_SIZE: "32M"
      INNODB_FLUSH_LOG_AT_TRX_COMMIT: "1"
      INNODB_LOCK_WAIT_TIMEOUT: "300"
      TZ: "America/São Paulo"
    command: mysqld --sql_mode="ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION" --max_allowed_packet=10240M --innodb_lock_wait_timeout=300 && mysql -u root -e "UPDATE cliniccentral.db_servers SET DNS = 'feegow-mysql' WHERE id = 1;
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/dumps:/docker-entrypoint-initdb.d
#    healthcheck:
#      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p" ]
#      interval: 20s
#      timeout: 5s
#      retries: 5
    networks:
      feegow:
        ipv4_address: 1.1.1.3

networks:
  feegow:
    driver: nat
    ipam:
      driver: default
      config:
        - subnet: 1.1.0.0/16

