version: '3'
services:
  feegow-web:
    platform: windows
    container_name: feegow-web
    hostname: feegow-web
    network_mode: nat
    links:
      - feegow-mysql
    build:
      context: iis
      dockerfile: Dockerfile
    image: asp-classic:feegow
    ports:
      - "880:80"
      - "8172:8172"
      - "8000:8000"
    networks:
      feegow:
        ipv4_address: 1.1.1.2
    environment:
#      - FC_MYSQL_HOST=localhost:3307
#      - FC_MYSQL_HOST=feegow-mysql:3306
      - FC_MYSQL_HOST=feegow-mysql:3306
      - FC_MYSQL_USER=root
      #- FC_MYSQL_PASSWORD=""
      - FC_MASTER=123456
      - FC_MYSQL_DATABASE=cliniccentral
      - FC_MYSQL_DRIVER="MySQL ODBC 8.0 ANSI Driver"
      - FC_PWD_SALT=F33g0W_Pwd4_
      #- FC_SRC_PATH="C:/inetpub/wwwroot"
      - FC_APP_ENV=local
    volumes:
      - C:/Users/bruno/VSCodeProjects/feegowclinic-v7:C:/inetpub/wwwroot
      - C:\Users\bruno\PhpstormProjects\feegow\feegow-api:C:/feegow-api
    #      - C:/Users/19926/VSCodeProjects/teste-docker:C:/inetpub/wwwroot
    depends_on:
      - feegow-mysql
    command:
      - c:/xampp/php/php.exe c:/feegow-api/artisan serve --port=8000

  feegow-mysql:
    platform: linux/x86_64
    container_name: feegow-mysql
    hostname: feegow-mysql
    network_mode: nat
    links:
      - feegow-web
    build:
      context: mysql
      dockerfile: Dockerfile
    image: mysql:5.7.38
    ports:
      - "3307:3306"
#      - "33060:33060"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      ROW_FORMAT: "DYNAMIC"
      INNODB_DEFAULT_ROW_FORMAT: "dynamic"
      SQL_MODE: "ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
      INNODB_BUFFER_POOL_SIZE: "64M"
      INNODB_LOG_FILE_SIZE: "5M"
      INNODB_LOG_BUFFER_SIZE: "32M"
      INNODB_FLUSH_LOG_AT_TRX_COMMIT: "1"
      INNODB_LOCK_WAIT_TIMEOUT: "300"
      TZ: "America/São Paulo"
    command: mysqld --sql_mode="ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION" --max_allowed_packet=10240M --innodb_lock_wait_timeout=300
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/dumps:/docker-entrypoint-initdb.d
    networks:
      feegow:
        ipv4_address: 1.1.1.3

#  feegow-api:
#    platform: linux
#    container_name: feegow-api
#    hostname: feegow-api
#    network_mode: nat
#    links:
#      - feegow-mysql
#      - feegow-web
#    build:
#        context: php
#        dockerfile: Dockerfile
#    image: php:feegow-api
#    ports:
#      - "8800:80"
##    command:
##      - "php artisan serve"
#    volumes:
#      - C:/Users/bruno/PhpstormProjects/feegow/feegow-api:/var/www/html
#    networks:
#      feegow:
#        ipv4_address: 1.1.1.4

networks:
    feegow:
        driver: nat
        ipam:
            driver: default
            config:
                - subnet: 1.1.0.0/16