#write docker-compse.yml to build up containers running on the same network with iis and mysql
#copy the site content from this computaer ./feegowclinic-v7 to c:\inetpub\wwwroot folder in the iis container
#copy the database to mysql container

version: '3.8'
services:
  iis:
    container_name: 'asp-classic'
    build:
      context: ./iis
      dockerfile: Dockerfile-IIS
#      args:
#        - "IIS_VERSION=10.0.19041.1"
    image:
      iis:asp-classic
    ports:
      - "880:80"
      - "8172:8172"
    networks:
      iis_network:
        ipv4_address: 10.1.1.2
    volumes:
#      - c:\Users\bruno\VSCodeProjects\feegowclinic-v7:c:\inetpub\wwwroot\feegowclinic-v7
      - C:\Users\bruno\VSCodeProjects\teste-docker:c:\inetpub\wwwroot
#      - type: bind
#        read_only: false
#        source: C:\Users\bruno\VSCodeProjects\feegowclinic-v7
#        target: C:\inetpub\wwwroot\feegowclinic-v7

    environment:
      FC_APP_ENV: "local"
      FC_MASTER: "123456"
      FC_MYSQL_DATABASE: "cliniccentral"
      FC_MYSQL_DRIVER: "MySQL ODBC 8.0 ANSI Driver"
      FC_MYSQL_HOST: "mysql"
      FC_MYSQL_PASSWORD: ""
      FC_MYSQL_USER: "root"
      FC_PWD_SALT: "F33g0W_Pwd4_"
      FC_SRC_PATH: "c:/inetpub/wwwroot/feegowclinic-v7"
#    command:
#      powershell -Command "icacls '\inetpub\wwwroot' /grant Everyone:F /t; Start-Service w3svc;"

#  mysql:
#    container_name: 'mysql-5.7'
#    platform: linux
#    build:
#      context: ./mysql
#      dockerfile: Dockerfile-MySQL
#    image: mysql:5.7
#    ports:
#      - "33306:3306"
#    environment:
#      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
#      ROW_FORMAT: "DYNAMIC"
#      INNODB_DEFAULT_ROW_FORMAT: "dynamic"
#      SQL_MODE: "ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
#      INNODB_BUFFER_POOL_SIZE: "64M"
#      INNODB_LOG_FILE_SIZE: "5M"
#      INNODB_LOG_BUFFER_SIZE: "32M"
#      INNODB_FLUSH_LOG_AT_TRX_COMMIT: "1"
#      INNODB_LOCK_WAIT_TIMEOUT: "300"
#      TZ: "America/São Paulo"
#    command: mysqld --sql_mode="ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION" --max_allowed_packet=10240M --innodb_lock_wait_timeout=300
#    volumes:
#      - .\mysql\conf.d:/etc/mysql/conf.d/
#      - .\mysql\db:/docker-entrypoint-initdb.d/
#    networks:
#      - iis_network

#  php:
#    container_name: 'php-5.6'
#    platform: linux
#    build:
#      context: ./php
#      dockerfile: Dockerfile-PHP
#      args:
#        - "PHP_VERSION=5.6"
#    image:
#      php:5.6
#    networks:
#      - iis_network
#

networks:
  iis_network:
    driver: nat
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/16