#baixa a imagem do windows server core
FROM mcr.microsoft.com/windows/servercore/iis
#define o shell
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]

#cria pasta e copia arquivos de instalação do módulo de rewrite do iis e do driver odbc do mysql
RUN md c:/msi
COPY msi/ c:/msi/
#instala o módulo de rewrite do iis e o driver odbc do mysql
RUN Start-Process 'c:/msi/rewrite_amd64_en-US.msi' '/qn' -PassThru | Wait-Process;
RUN Start-Process 'c:/msi/mysql-connector-odbc-8.0.32-winx64.msi' '/qn' -PassThru | Wait-Process;

#instala os recursos do iis
RUN Install-WindowsFeature -Name Web-ASP, Web-CGI, Web-ISAPI-Ext, Web-ISAPI-Filter, Web-Includes, Web-HTTP-Errors, Web-Common-HTTP, Web-Performance, WAS;
#instala o módulo de gerenciamento do iis (testar sem isso)
RUN Import-module IISAdministration;

RUN net user iisadmin "Password~1234" /ADD; \
	net localgroup administrators iisadmin /add
RUN Install-WindowsFeature Web-Mgmt-Service; \
	Set-ItemProperty -Path HKLM:\SOFTWARE\Microsoft\WebManagement\Server -Name EnableRemoteManagement -Value 1; \
	Set-Service WMSVC -StartupType Automatic

#desbloqueia as seções do web.config
RUN c:\windows\system32\inetsrv\appcmd.exe unlock config /section:system.webServer/asp
RUN c:\windows\system32\inetsrv\appcmd.exe unlock config /section:system.webServer/handlers
RUN c:\windows\system32\inetsrv\appcmd.exe unlock config /section:system.webServer/modules

#configura opções do iis
RUN c:\windows\system32\inetsrv\appcmd.exe set config -section:asp -scriptErrorSentToBrowser:true
RUN c:\windows\system32\inetsrv\appcmd.exe set config -section:asp -appAllowDebugging:true
RUN c:\windows\system32\inetsrv\appcmd.exe set config -section:asp -appAllowClientDebug:true
RUN c:\windows\system32\inetsrv\appcmd.exe set config -section:asp -enableParentPaths:true
RUN c:\windows\system32\inetsrv\appcmd.exe set config -section:asp -debug:true

#enable default document
RUN c:\windows\system32\inetsrv\appcmd.exe set config -section:system.webServer/defaultDocument -enabled:true
#RUN New-WebConfiguration /system.webServer/defaultDocument -Metadata.Add @{"value"="index.asp"} -psPath machine/webroot/apphost
#RUN c:\windows\system32\inetsrv\appcmd.exe set config -section:system.webServer/defaultDocument /enabled:true /+files.[@start, value='index.asp']
#RUN c:\windows\system32\inetsrv\appcmd.exe set config -section:system.webServer/defaultDocument /enabled:true /+"files.[@start,index.asp='index.asp']"
#RUN c:\windows\system32\inetsrv\appcmd.exe set config -section:system.webServer/defaultDocument /+"files.[value='index.asp']" /commit:apphost
#RUN c:\windows\system32\inetsrv\appcmd.exe set config -section:system.webServer/defaultDocument /+files.[value='index.asp']
#RUN c:\windows\system32\inetsrv\appcmd.exe set config -section:system.webServer/defaultDocument /+files.[value='home.html']

#altera permissoes na pasta wwwroot
RUN icacls 'c:/inetpub/wwwroot' /grant Everyone:F /t


#expõe a porta 80
EXPOSE 80